EXAMPLES_TRAIN = [
    ("What is the user name for ID 35?", "Charlie"),
    ("What is the location ID for Miami?", "5"),
    ("What city has location ID 4?", "Houston"),
    ("What is the current time in Miami?", "2023-11-14 1:20 PM"),
    ("What is the current weather in Houston?", "Rainy, Temperature: 55°F"),
    ("what is frank the cat's user id?", "43"),
    ("what is donna's email address?", "donna@example.com"),
    ("what is bob's favorite color?", "orange"),
    ("Name the favorite foods of Alice.", "Pizza, Chocolate, Sushi"),
    ("list the allergens in burger", "gluten, dairy"),
    ("How many calories are in Ice Cream?", "200 calories"),
    ("What is the name of food with id 3?", "Sushi"),
    ("Does the current user live in Chicago?", "yes"),
    ("Where does Eve live? (city name)", "Miami"),
    ("Do Bob and Charlie live in the same city?", "no"),
    ("What is the current user's email address?", "charlie@yahoo.com"),
    ("List the current weather where Alice lives.", "Partly Cloudy, Temperature: 68°F"),
    ("How many users have the favorite color yellow?", "2"),
    ("Find users named 'Donna'. How many are there?", "1"),
    ("What is the city for location ID 5?", "Miami"),
    ("What is Frank The Cat's favorite color?", "yellow"),
    ("Which allergens are in Sushi?", "fish, soy"),
    ("Is it raining in Houston right now?", "yes"),
]