EXAMPLES_TEST = [
    ("What is the city for location ID 1?", "New York"),
    ("What is the name of food with id 6?", "Pasta"),
    ("what is eve's user id?", "42"),
    ("get the current user id", "35"),
    ("How many users by the name of bob?", "1"),
    ("what is alice's email address?", "alice@gmail.com"),
    ("find donna's favorite color", "green"),
    ("weather in LA right now?", "Sunny, Temperature: 75°F"),
    ("time in chicago", "2023-11-14 11:15 AM"),
    ("list the allergens in chocolate", "milk, soy"),
    ("If i eat a serving of pizza, how many calories will I consume?", "285 calories"),
    ("what is the current users favorite color?", "yellow"),
    ("eve ate a serving of sushi, what allergens was she exposed to?", "fish, soy"),
    ("Frank who is Even's friend is allergic to dairy. Can he eat the salad?", "yes"),
    ("what is the current users favorite color and name?", "yellow and Charlie"),
    ("whats the name of the city where bob lives?", "Los Angeles"),
    ("Donna is about to go outside. Does she need an umbrella?", "yes"),
    ("Is it likely that Donna is awake right now?", "yes"),
    ("do alice and charlie use the same email provider?", "no"),
    ("Is it likely that Donna is outside with an umbrella at this time?", "yes"),
    ("do bob and alice live in the same city?", "no"),
]