# Auto-generated by synthetic_gen_tasks.py; DO NOT EDIT.

from .types import Task, Action


TASKS_TRAIN = [
    Task(
        annotator="synthetic",
        user_id='liam_thomas_8833',
        instruction="Your name is Liam Thomas and your email is liam.thomas4271@example.com and your zip code is 20119. You are pessimistic, optimistic, logical, sad. For #W3761872, modify Espresso Machine {'capacity': '2L', 'pressure': '9 bar', 'type': 'automatic'} to {'capacity': '1L', 'pressure': '19 bar', 'type': 'capsule'}; via paypal_8229936.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W3761872', 'item_ids': ['3709608322'], 'new_item_ids': ['6200867091'], 'payment_method_id': 'paypal_8229936'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='olivia_ito_3591',
        instruction="Your name is Olivia Ito and your email is olivia.ito5204@example.com and your zip code is 80218. You are polite, pessimistic. For #W3657213, change payment to credit_card_9753331. For #W3657213, modify Digital Camera {'resolution': '24MP', 'storage': 'SD card', 'zoom': '3x'} to {'resolution': '30MP', 'storage': 'CF card', 'zoom': '5x'}; via paypal_8049766. Cancel order #W7941031 because no longer needed.",
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W3657213', 'payment_method_id': 'credit_card_9753331'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W3657213', 'item_ids': ['5996159312'], 'new_item_ids': ['6384525445'], 'payment_method_id': 'paypal_8049766'},
            ),
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W7941031', 'reason': 'no longer needed'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='liam_lee_5696',
        instruction="Your name is Liam Lee and your email is liam.lee9297@example.com and your zip code is 76176. You are patient, logical. For #W7208030, change address to {'order_id': '#W7208030', 'address1': '181 Elm Avenue', 'address2': 'Suite 871', 'city': 'Fort Worth', 'country': 'USA', 'state': 'TX', 'zip': '76176'}.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W7208030', 'address1': '181 Elm Avenue', 'address2': 'Suite 871', 'city': 'Fort Worth', 'state': 'TX', 'country': 'USA', 'zip': '76176'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ava_nguyen_6646',
        instruction="Your name is Ava Nguyen and your email is ava.nguyen2868@example.com and your zip code is 94128. You are shy, happy, sad. For #W8668939, exchange Grill {'features': 'none', 'size': 'portable', 'type': 'electric'} to {'features': 'side burner', 'size': 'portable', 'type': 'electric'}; via credit_card_5683823. For #W9892465, change payment to credit_card_5683823.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W8668939', 'item_ids': ['1120917161'], 'new_item_ids': ['3876764226'], 'payment_method_id': 'credit_card_5683823'},
            ),
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W9892465', 'payment_method_id': 'credit_card_5683823'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='emma_kovacs_5477',
        instruction="Your name is Emma Kovacs and your email is emma.kovacs5723@example.com and your zip code is 95111. You are direct, logical, polite. For #W3618959, change address to {'order_id': '#W3618959', 'address1': '670 Park Avenue', 'address2': 'Suite 249', 'city': 'San Diego', 'country': 'USA', 'state': 'CA', 'zip': '92179'}. For #W7109609, modify Vacuum Cleaner {'bagged/bagless': 'bagless', 'features': 'cordless', 'type': 'robotic'} to {'bagged/bagless': 'bagless', 'features': 'pet hair removal', 'type': 'robotic'}; via gift_card_9246707. Cancel order #W3618959 because no longer needed.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W3618959', 'address1': '670 Park Avenue', 'address2': 'Suite 249', 'city': 'San Diego', 'state': 'CA', 'country': 'USA', 'zip': '92179'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W7109609', 'item_ids': ['4806644905'], 'new_item_ids': ['4965355367'], 'payment_method_id': 'gift_card_9246707'},
            ),
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W3618959', 'reason': 'no longer needed'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='anya_brown_2024',
        instruction="Your name is Anya Brown and your email is anya.brown8893@example.com and your zip code is 10121. You are happy, direct. For #W1170711, change address to {'order_id': '#W1170711', 'address1': '901 Laurel Lane', 'address2': 'Suite 413', 'city': 'New York', 'country': 'USA', 'state': 'NY', 'zip': '10121'}.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W1170711', 'address1': '901 Laurel Lane', 'address2': 'Suite 413', 'city': 'New York', 'state': 'NY', 'country': 'USA', 'zip': '10121'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='yusuf_garcia_5427',
        instruction="Your name is Yusuf Garcia and your email is yusuf.garcia5261@example.com and your zip code is 10155. You are shy, curious, patient. For #W5763385, exchange Cycling Helmet {'color': 'black', 'size': 'S', 'ventilation': 'medium'} to {'color': 'red', 'size': 'M', 'ventilation': 'high'}; via gift_card_6337815.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W5763385', 'item_ids': ['5537798301'], 'new_item_ids': ['8573379326'], 'payment_method_id': 'gift_card_6337815'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='lei_li_6575',
        instruction="Your name is Lei Li and your email is lei.li8350@example.com and your zip code is 85033. You are happy, outgoing. For #W6289770, exchange Luggage Set {'color': 'red', 'material': 'hardshell', 'piece count': '2-piece'} to {'color': 'blue', 'material': 'softshell', 'piece count': '3-piece'}; via credit_card_4466831. For #W3414433, modify Electric Kettle {'capacity': '1L', 'color': 'black', 'material': 'stainless steel'} to {'capacity': '1L', 'color': 'white', 'material': 'glass'}; via credit_card_4466831.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W6289770', 'item_ids': ['8964750292'], 'new_item_ids': ['6301799585'], 'payment_method_id': 'credit_card_4466831'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W3414433', 'item_ids': ['7602931732'], 'new_item_ids': ['5268233322'], 'payment_method_id': 'credit_card_4466831'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='james_wilson_1842',
        instruction="Your name is James Wilson and your email is james.wilson1461@example.com and your zip code is 80224. You are organized, busy. For #W7826235, exchange Bookshelf {'color': 'white', 'height': '3 ft', 'material': 'glass'} to {'color': 'white', 'height': '4 ft', 'material': 'wood'}; via credit_card_7871433.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W7826235', 'item_ids': ['2989722512'], 'new_item_ids': ['8920458606'], 'payment_method_id': 'credit_card_7871433'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='evelyn_ito_7643',
        instruction='Your name is Evelyn Ito and your email is evelyn.ito2168@example.com and your zip code is 92127. You are shy, flexible, cautious. For #W6207110, change payment to paypal_5377635.',
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W6207110', 'payment_method_id': 'paypal_5377635'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='mei_kovacs_5767',
        instruction="Your name is Mei Kovacs and your email is mei.kovacs4296@example.com and your zip code is 43295. You are shy, busy, direct, organized. For #W2022128, change address to {'order_id': '#W2022128', 'address1': '806 Park Avenue', 'address2': 'Suite 429', 'city': 'Columbus', 'country': 'USA', 'state': 'OH', 'zip': '43295'}.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W2022128', 'address1': '806 Park Avenue', 'address2': 'Suite 429', 'city': 'Columbus', 'state': 'OH', 'country': 'USA', 'zip': '43295'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='fatima_wilson_6873',
        instruction="Your name is Fatima Wilson and your email is fatima.wilson5906@example.com and your zip code is 78746. You are polite, relaxing. For #W7990410, exchange Headphones {'color': 'blue', 'connectivity': 'wired', 'type': 'over-ear'} to {'color': 'black', 'connectivity': 'wireless', 'type': 'in-ear'}; via paypal_7685859. Cancel order #W1443906 because ordered by mistake.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W7990410', 'item_ids': ['5635439102'], 'new_item_ids': ['7184044281'], 'payment_method_id': 'paypal_7685859'},
            ),
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W1443906', 'reason': 'ordered by mistake'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='emma_santos_9753',
        instruction='Your name is Emma Santos and your email is emma.santos7683@example.com and your zip code is 78228. You are patient, polite. For #W9903153, change payment to credit_card_5869505.',
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W9903153', 'payment_method_id': 'credit_card_5869505'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='olivia_ito_3591',
        instruction='Your name is Olivia Ito and your email is olivia.ito5204@example.com and your zip code is 80218. You are flexible, outgoing. For #W3657213, change payment to credit_card_9753331.',
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W3657213', 'payment_method_id': 'credit_card_9753331'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ethan_sanchez_2952',
        instruction='Your name is Ethan Sanchez and your email is ethan.sanchez6360@example.com and your zip code is 78782. You are creative, busy. Return #W9250394 via paypal_3574041: Dumbbell Set;',
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W9250394', 'item_ids': ['7159180318'], 'payment_method_id': 'paypal_3574041'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ivan_santos_6635',
        instruction='Your name is Ivan Santos and your email is ivan.santos3158@example.com and your zip code is 75277. You are independent, busy, outgoing. Cancel order #W8770097 because no longer needed.',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W8770097', 'reason': 'no longer needed'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ethan_sanchez_2952',
        instruction='Your name is Ethan Sanchez and your email is ethan.sanchez6360@example.com and your zip code is 78782. You are direct, flexible. Return #W9250394 via paypal_3574041: Dumbbell Set; For #W9102111, change payment to paypal_3574041.',
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W9250394', 'item_ids': ['7159180318'], 'payment_method_id': 'paypal_3574041'},
            ),
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W9102111', 'payment_method_id': 'paypal_3574041'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='mia_thomas_4629',
        instruction='Your name is Mia Thomas and your email is mia.thomas7243@example.com and your zip code is 60654. You are direct, confident. Cancel order #W5208989 because no longer needed.',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W5208989', 'reason': 'no longer needed'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='sophia_patel_6833',
        instruction="Your name is Sophia Patel and your email is sophia.patel9841@example.com and your zip code is 76169. You are direct, confident. For #W7905419, modify Perfume {'gender': 'men', 'scent family': 'oriental', 'size': '100ml'} to {'gender': 'men', 'scent family': 'oriental', 'size': '30ml'}; via credit_card_6017489.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W7905419', 'item_ids': ['5421902839'], 'new_item_ids': ['1325156478'], 'payment_method_id': 'credit_card_6017489'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='fatima_wilson_6873',
        instruction="Your name is Fatima Wilson and your email is fatima.wilson5906@example.com and your zip code is 78746. You are curious, polite, flexible. For #W7990410, exchange Headphones {'color': 'blue', 'connectivity': 'wired', 'type': 'over-ear'} to {'color': 'black', 'connectivity': 'wireless', 'type': 'in-ear'}; via paypal_7685859. Return #W4556683 via credit_card_9557278: Electric Kettle; Water Bottle; Wireless Earbuds; Espresso Machine; Bluetooth Speaker;",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W7990410', 'item_ids': ['5635439102'], 'new_item_ids': ['7184044281'], 'payment_method_id': 'paypal_7685859'},
            ),
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W4556683', 'item_ids': ['9132333852', '7533802601', '8555936349', '3709608322', '4716977452'], 'payment_method_id': 'credit_card_9557278'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='omar_johnson_2562',
        instruction='Your name is Omar Johnson and your email is omar.johnson6791@example.com and your zip code is 32228. You are shy, confident, optimistic. For #W8797321, change payment to paypal_6053880.',
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W8797321', 'payment_method_id': 'paypal_6053880'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='daiki_kovacs_2546',
        instruction="Your name is Daiki Kovacs and your email is daiki.kovacs3314@example.com and your zip code is 43196. You are organized, patient. For #W2259015, exchange Tea Kettle {'capacity': '2 liters', 'material': 'ceramic', 'stovetop compatibility': 'gas'} to {'capacity': '1.5 liters', 'material': 'stainless steel', 'stovetop compatibility': 'induction'}; via paypal_9103096.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W2259015', 'item_ids': ['3761330360'], 'new_item_ids': ['3738831434'], 'payment_method_id': 'paypal_9103096'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='amelia_wilson_4614',
        instruction='Your name is Amelia Wilson and your email is amelia.wilson1598@example.com and your zip code is 75215. You are cautious, organized. Cancel order #W3062096 because no longer needed.',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W3062096', 'reason': 'no longer needed'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='aarav_gonzalez_5113',
        instruction='Your name is Aarav Gonzalez and your email is aarav.gonzalez9269@example.com and your zip code is 78268. You are independent, patient. Cancel order #W9160732 because ordered by mistake.',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W9160732', 'reason': 'ordered by mistake'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='daiki_muller_8062',
        instruction="Your name is Daiki Muller and your email is daiki.muller6278@example.com and your zip code is 94157. You are confident, direct, shy. For #W7822344, change address to {'order_id': '#W7822344', 'address1': '241 Maple Drive', 'address2': 'Suite 840', 'city': 'San Francisco', 'country': 'USA', 'state': 'CA', 'zip': '94157'}.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W7822344', 'address1': '241 Maple Drive', 'address2': 'Suite 840', 'city': 'San Francisco', 'state': 'CA', 'country': 'USA', 'zip': '94157'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='emma_kovacs_5477',
        instruction="Your name is Emma Kovacs and your email is emma.kovacs5723@example.com and your zip code is 95111. You are optimistic, curious, polite. For #W3618959, change address to {'order_id': '#W3618959', 'address1': '670 Park Avenue', 'address2': 'Suite 249', 'city': 'San Diego', 'country': 'USA', 'state': 'CA', 'zip': '92179'}.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W3618959', 'address1': '670 Park Avenue', 'address2': 'Suite 249', 'city': 'San Diego', 'state': 'CA', 'country': 'USA', 'zip': '92179'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='olivia_khan_9030',
        instruction="Your name is Olivia Khan and your email is olivia.khan2360@example.com and your zip code is 92110. You are shy, pessimistic, logical. For #W3840181, change payment to credit_card_7376788. For #W3840181, modify T-Shirt {'color': 'red', 'material': 'cotton', 'size': 'S', 'style': 'crew neck'} to {'color': 'purple', 'material': 'polyester', 'size': 'S', 'style': 'v-neck'}; via credit_card_1936578.",
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W3840181', 'payment_method_id': 'credit_card_7376788'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W3840181', 'item_ids': ['3542102174'], 'new_item_ids': ['9647292434'], 'payment_method_id': 'credit_card_1936578'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='yusuf_garcia_3055',
        instruction="Your name is Yusuf Garcia and your email is yusuf.garcia2909@example.com and your zip code is 20080. You are cautious, curious. For #W2564042, modify Laptop {'color': 'black', 'processor': 'i7', 'ram': '32GB', 'screen size': '13-inch', 'storage': '512GB SSD'} to {'color': 'space grey', 'processor': 'i5', 'ram': '32GB', 'screen size': '15-inch', 'storage': '256GB SSD'}; via credit_card_8405687.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W2564042', 'item_ids': ['1657832319'], 'new_item_ids': ['2216662955'], 'payment_method_id': 'credit_card_8405687'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ava_nguyen_6646',
        instruction="Your name is Ava Nguyen and your email is ava.nguyen2868@example.com and your zip code is 94128. You are patient, sad, busy, happy. For #W9892465, change address to {'order_id': '#W9892465', 'address1': '814 Maple Drive', 'address2': 'Suite 313', 'city': 'San Francisco', 'country': 'USA', 'state': 'CA', 'zip': '94128'}. For #W8367380, change address to {'order_id': '#W8367380', 'address1': '373 Cedar Street', 'address2': 'Suite 830', 'city': 'Los Angeles', 'country': 'USA', 'state': 'CA', 'zip': '90450'}. For #W9892465, modify Smart Watch {'band material': 'leather', 'color': 'silver', 'display': 'LCD'} to {'band material': 'leather', 'color': 'gold', 'display': 'AMOLED'}; via gift_card_1994993. For #W9232383, modify Headphones {'color': 'white', 'connectivity': 'wireless', 'type': 'on-ear'} to {'color': 'black', 'connectivity': 'wired', 'type': 'over-ear'}; via gift_card_1994993.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W9892465', 'address1': '814 Maple Drive', 'address2': 'Suite 313', 'city': 'San Francisco', 'state': 'CA', 'country': 'USA', 'zip': '94128'},
            ),
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W8367380', 'address1': '373 Cedar Street', 'address2': 'Suite 830', 'city': 'Los Angeles', 'state': 'CA', 'country': 'USA', 'zip': '90450'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W9892465', 'item_ids': ['9811090008'], 'new_item_ids': ['5694328282'], 'payment_method_id': 'gift_card_1994993'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W9232383', 'item_ids': ['9805150490'], 'new_item_ids': ['3374679624'], 'payment_method_id': 'gift_card_1994993'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='olivia_ito_3591',
        instruction="Your name is Olivia Ito and your email is olivia.ito5204@example.com and your zip code is 80218. You are optimistic, curious. For #W3657213, change payment to credit_card_9753331. For #W3657213, modify Digital Camera {'resolution': '24MP', 'storage': 'SD card', 'zoom': '3x'} to {'resolution': '30MP', 'storage': 'CF card', 'zoom': '5x'}; via paypal_8049766.",
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W3657213', 'payment_method_id': 'credit_card_9753331'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W3657213', 'item_ids': ['5996159312'], 'new_item_ids': ['6384525445'], 'payment_method_id': 'paypal_8049766'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ava_nguyen_6646',
        instruction="Your name is Ava Nguyen and your email is ava.nguyen2868@example.com and your zip code is 94128. You are sad, pessimistic, messy, curious. For #W9892465, change address to {'order_id': '#W9892465', 'address1': '814 Maple Drive', 'address2': 'Suite 313', 'city': 'San Francisco', 'country': 'USA', 'state': 'CA', 'zip': '94128'}.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W9892465', 'address1': '814 Maple Drive', 'address2': 'Suite 313', 'city': 'San Francisco', 'state': 'CA', 'country': 'USA', 'zip': '94128'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='amelia_wilson_4614',
        instruction='Your name is Amelia Wilson and your email is amelia.wilson1598@example.com and your zip code is 75215. You are optimistic, polite, sad, cautious. Cancel order #W3062096 because ordered by mistake.',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W3062096', 'reason': 'ordered by mistake'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='olivia_silva_7273',
        instruction="Your name is Olivia Silva and your email is olivia.silva3776@example.com and your zip code is 32240. You are happy, patient. For #W7613749, change address to {'order_id': '#W7613749', 'address1': '557 Cedar Street', 'address2': 'Suite 120', 'city': 'Jacksonville', 'country': 'USA', 'state': 'FL', 'zip': '32240'}.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W7613749', 'address1': '557 Cedar Street', 'address2': 'Suite 120', 'city': 'Jacksonville', 'state': 'FL', 'country': 'USA', 'zip': '32240'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='james_martin_1500',
        instruction="Your name is James Martin and your email is james.martin9857@example.com and your zip code is 92112. You are happy, logical. For #W3043531, modify Backpack {'color': 'green', 'compartment': 'camera', 'material': 'polyester', 'size': 'small'} to {'color': 'green', 'compartment': 'laptop', 'material': 'polyester', 'size': 'small'}; via credit_card_7083997.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W3043531', 'item_ids': ['9851293632'], 'new_item_ids': ['3557711149'], 'payment_method_id': 'credit_card_7083997'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='mei_gonzalez_4785',
        instruction='Your name is Mei Gonzalez and your email is mei.gonzalez8775@example.com and your zip code is 95170. You are cautious, patient. Return #W7303089 via credit_card_4387170: Pet Bed;',
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W7303089', 'item_ids': ['7381052709'], 'payment_method_id': 'credit_card_4387170'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='daiki_muller_8062',
        instruction="Your name is Daiki Muller and your email is daiki.muller6278@example.com and your zip code is 94157. You are sad, flexible. For #W7822344, modify Electric Kettle {'capacity': '1L', 'color': 'silver', 'material': 'stainless steel'} to {'capacity': '1.5L', 'color': 'black', 'material': 'plastic'}; via gift_card_8385925.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W7822344', 'item_ids': ['8142779083'], 'new_item_ids': ['5428723833'], 'payment_method_id': 'gift_card_8385925'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='james_martin_1500',
        instruction='Your name is James Martin and your email is james.martin9857@example.com and your zip code is 92112. You are optimistic, pessimistic, sad, independent. For #W3529525, change payment to credit_card_6932154.',
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W3529525', 'payment_method_id': 'credit_card_6932154'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='raj_kim_8554',
        instruction='Your name is Raj Kim and your email is raj.kim9998@example.com and your zip code is 32145. You are logical, busy. Return #W5697187 via credit_card_4591662: Hiking Boots; Electric Toothbrush;',
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W5697187', 'item_ids': ['5676696062', '6164262152'], 'payment_method_id': 'credit_card_4591662'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='olivia_silva_7273',
        instruction="Your name is Olivia Silva and your email is olivia.silva3776@example.com and your zip code is 32240. You are direct, flexible, pessimistic. For #W7613749, change address to {'order_id': '#W7613749', 'address1': '557 Cedar Street', 'address2': 'Suite 120', 'city': 'Jacksonville', 'country': 'USA', 'state': 'FL', 'zip': '32240'}. Cancel order #W1524774 because ordered by mistake.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W7613749', 'address1': '557 Cedar Street', 'address2': 'Suite 120', 'city': 'Jacksonville', 'state': 'FL', 'country': 'USA', 'zip': '32240'},
            ),
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W1524774', 'reason': 'ordered by mistake'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ivan_khan_7475',
        instruction="Your name is Ivan Khan and your email is ivan.khan6479@example.com and your zip code is 28243. You are logical, happy. For #W5782623, change payment to paypal_7729105. For #W5782623, change address to {'order_id': '#W5782623', 'address1': '711 Laurel Lane', 'address2': 'Suite 348', 'city': 'Charlotte', 'country': 'USA', 'state': 'NC', 'zip': '28243'}.",
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W5782623', 'payment_method_id': 'paypal_7729105'},
            ),
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W5782623', 'address1': '711 Laurel Lane', 'address2': 'Suite 348', 'city': 'Charlotte', 'state': 'NC', 'country': 'USA', 'zip': '28243'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='mohamed_li_1979',
        instruction='Your name is Mohamed Li and your email is mohamed.li8414@example.com and your zip code is 43209. You are organized, creative. Return #W8864622 via paypal_6045911: Jigsaw Puzzle;',
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W8864622', 'item_ids': ['5172162216'], 'payment_method_id': 'paypal_6045911'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='fatima_wilson_6873',
        instruction="Your name is Fatima Wilson and your email is fatima.wilson5906@example.com and your zip code is 78746. You are patient, happy. For #W7990410, exchange Headphones {'color': 'blue', 'connectivity': 'wired', 'type': 'over-ear'} to {'color': 'black', 'connectivity': 'wireless', 'type': 'in-ear'}; via paypal_7685859.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W7990410', 'item_ids': ['5635439102'], 'new_item_ids': ['7184044281'], 'payment_method_id': 'paypal_7685859'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='anya_brown_2024',
        instruction="Your name is Anya Brown and your email is anya.brown8893@example.com and your zip code is 10121. You are independent, relaxing, sad, messy. For #W1170711, change address to {'order_id': '#W1170711', 'address1': '901 Laurel Lane', 'address2': 'Suite 413', 'city': 'New York', 'country': 'USA', 'state': 'NY', 'zip': '10121'}. For #W1170711, modify Desk Lamp {'brightness': 'medium', 'color': 'black', 'power source': 'USB'} to {'brightness': 'high', 'color': 'black', 'power source': 'AC adapter'}; via credit_card_3414703.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W1170711', 'address1': '901 Laurel Lane', 'address2': 'Suite 413', 'city': 'New York', 'state': 'NY', 'country': 'USA', 'zip': '10121'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W1170711', 'item_ids': ['6805564527'], 'new_item_ids': ['7624783998'], 'payment_method_id': 'credit_card_3414703'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='aarav_moore_6923',
        instruction='Your name is Aarav Moore and your email is aarav.moore6937@example.com and your zip code is 85041. You are shy, relaxing, independent. Return #W8496475 via paypal_4751854: Tea Kettle;',
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W8496475', 'item_ids': ['7274158061'], 'payment_method_id': 'paypal_4751854'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='harper_brown_7363',
        instruction="Your name is Harper Brown and your email is harper.brown3965@example.com and your zip code is 76112. You are messy, logical. For #W2693718, exchange Sunglasses {'frame color': 'black', 'frame material': 'plastic', 'lens color': 'brown', 'lens type': 'polarized'} to {'frame color': 'brown', 'frame material': 'plastic', 'lens color': 'brown', 'lens type': 'polarized'}; via paypal_2306935.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W2693718', 'item_ids': ['4358482460'], 'new_item_ids': ['9672174103'], 'payment_method_id': 'paypal_2306935'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='lei_li_6575',
        instruction="Your name is Lei Li and your email is lei.li8350@example.com and your zip code is 85033. You are flexible, organized. For #W6289770, exchange Luggage Set {'color': 'red', 'material': 'hardshell', 'piece count': '2-piece'} to {'color': 'blue', 'material': 'softshell', 'piece count': '3-piece'}; via credit_card_4466831. For #W3414433, modify Electric Kettle {'capacity': '1L', 'color': 'black', 'material': 'stainless steel'} to {'capacity': '1L', 'color': 'white', 'material': 'glass'}; via credit_card_4466831. For #W5166363, modify Laptop {'color': 'space grey', 'processor': 'i5', 'ram': '8GB', 'screen size': '17-inch', 'storage': '1TB SSD'} to {'color': 'silver', 'processor': 'i5', 'ram': '16GB', 'screen size': '13-inch', 'storage': '1TB SSD'}; via credit_card_4466831.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W6289770', 'item_ids': ['8964750292'], 'new_item_ids': ['6301799585'], 'payment_method_id': 'credit_card_4466831'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W3414433', 'item_ids': ['7602931732'], 'new_item_ids': ['5268233322'], 'payment_method_id': 'credit_card_4466831'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W5166363', 'item_ids': ['3334537816'], 'new_item_ids': ['5052031638'], 'payment_method_id': 'credit_card_4466831'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='sofia_ahmed_9514',
        instruction='Your name is Sofia Ahmed and your email is sofia.ahmed2872@example.com and your zip code is 90819. You are curious, optimistic, independent, logical. Return #W2002395 via gift_card_6117300: Garden Hose;',
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W2002395', 'item_ids': ['3369928769'], 'payment_method_id': 'gift_card_6117300'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ivan_santos_6635',
        instruction='Your name is Ivan Santos and your email is ivan.santos3158@example.com and your zip code is 75277. You are pessimistic, optimistic. Cancel order #W8770097 because no longer needed. Cancel order #W5183325 because no longer needed.',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W8770097', 'reason': 'no longer needed'},
            ),
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W5183325', 'reason': 'no longer needed'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='yusuf_patel_7767',
        instruction="Your name is Yusuf Patel and your email is yusuf.patel5348@example.com and your zip code is 94117. You are curious, shy. For #W1052399, exchange Air Purifier {'features': 'night mode', 'filter type': 'HEPA', 'room size': 'large'} to {'features': 'night mode', 'filter type': 'HEPA', 'room size': 'small'}; via gift_card_3372949.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W1052399', 'item_ids': ['8302289002'], 'new_item_ids': ['7166996157'], 'payment_method_id': 'gift_card_3372949'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='olivia_khan_9030',
        instruction="Your name is Olivia Khan and your email is olivia.khan2360@example.com and your zip code is 92110. You are optimistic, organized. For #W3840181, change address to {'order_id': '#W3840181', 'address1': '360 Laurel Lane', 'address2': 'Suite 235', 'city': 'Indianapolis', 'country': 'USA', 'state': 'IN', 'zip': '46290'}.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W3840181', 'address1': '360 Laurel Lane', 'address2': 'Suite 235', 'city': 'Indianapolis', 'state': 'IN', 'country': 'USA', 'zip': '46290'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='emma_kovacs_5477',
        instruction="Your name is Emma Kovacs and your email is emma.kovacs5723@example.com and your zip code is 95111. You are shy, direct. For #W3618959, change address to {'order_id': '#W3618959', 'address1': '670 Park Avenue', 'address2': 'Suite 249', 'city': 'San Diego', 'country': 'USA', 'state': 'CA', 'zip': '92179'}. For #W7109609, modify Vacuum Cleaner {'bagged/bagless': 'bagless', 'features': 'cordless', 'type': 'robotic'} to {'bagged/bagless': 'bagless', 'features': 'pet hair removal', 'type': 'robotic'}; via gift_card_9246707.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W3618959', 'address1': '670 Park Avenue', 'address2': 'Suite 249', 'city': 'San Diego', 'state': 'CA', 'country': 'USA', 'zip': '92179'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W7109609', 'item_ids': ['4806644905'], 'new_item_ids': ['4965355367'], 'payment_method_id': 'gift_card_9246707'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='emma_santos_9753',
        instruction='Your name is Emma Santos and your email is emma.santos7683@example.com and your zip code is 78228. You are flexible, busy, direct. Cancel order #W2918688 because ordered by mistake.',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W2918688', 'reason': 'ordered by mistake'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ava_nguyen_6646',
        instruction="Your name is Ava Nguyen and your email is ava.nguyen2868@example.com and your zip code is 94128. You are flexible, pessimistic. For #W9892465, change address to {'order_id': '#W9892465', 'address1': '814 Maple Drive', 'address2': 'Suite 313', 'city': 'San Francisco', 'country': 'USA', 'state': 'CA', 'zip': '94128'}. For #W8367380, change address to {'order_id': '#W8367380', 'address1': '373 Cedar Street', 'address2': 'Suite 830', 'city': 'Los Angeles', 'country': 'USA', 'state': 'CA', 'zip': '90450'}. For #W9892465, modify Smart Watch {'band material': 'leather', 'color': 'silver', 'display': 'LCD'} to {'band material': 'leather', 'color': 'gold', 'display': 'AMOLED'}; via gift_card_1994993.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W9892465', 'address1': '814 Maple Drive', 'address2': 'Suite 313', 'city': 'San Francisco', 'state': 'CA', 'country': 'USA', 'zip': '94128'},
            ),
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W8367380', 'address1': '373 Cedar Street', 'address2': 'Suite 830', 'city': 'Los Angeles', 'state': 'CA', 'country': 'USA', 'zip': '90450'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W9892465', 'item_ids': ['9811090008'], 'new_item_ids': ['5694328282'], 'payment_method_id': 'gift_card_1994993'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='emma_santos_9753',
        instruction="Your name is Emma Santos and your email is emma.santos7683@example.com and your zip code is 78228. You are pessimistic, cautious, organized. For #W9903153, modify Water Bottle {'capacity': '750ml', 'color': 'red', 'material': 'stainless steel'} to {'capacity': '500ml', 'color': 'black', 'material': 'glass'}; via credit_card_5869505.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W9903153', 'item_ids': ['6777246137'], 'new_item_ids': ['8538875209'], 'payment_method_id': 'credit_card_5869505'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='harper_kim_2998',
        instruction='Your name is Harper Kim and your email is harper.kim4003@example.com and your zip code is 78222. You are creative, cautious. Cancel order #W8121088 because no longer needed.',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W8121088', 'reason': 'no longer needed'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='olivia_sanchez_2914',
        instruction='Your name is Olivia Sanchez and your email is olivia.sanchez1894@example.com and your zip code is 19116. You are cautious, flexible, outgoing, pessimistic. Cancel order #W5101035 because ordered by mistake.',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W5101035', 'reason': 'ordered by mistake'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ava_nguyen_6646',
        instruction="Your name is Ava Nguyen and your email is ava.nguyen2868@example.com and your zip code is 94128. You are sad, outgoing, shy. For #W8668939, exchange Grill {'features': 'none', 'size': 'portable', 'type': 'electric'} to {'features': 'side burner', 'size': 'portable', 'type': 'electric'}; via credit_card_5683823.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W8668939', 'item_ids': ['1120917161'], 'new_item_ids': ['3876764226'], 'payment_method_id': 'credit_card_5683823'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='isabella_sanchez_2068',
        instruction='Your name is Isabella Sanchez and your email is isabella.sanchez6218@example.com and your zip code is 85093. You are sad, organized, messy, outgoing. Return #W1713682 via paypal_8516781: Smart Watch; Hiking Boots; Bluetooth Speaker; Mechanical Keyboard; Makeup Kit;',
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W1713682', 'item_ids': ['1007724142', '3812493782', '5967152432', '4648814700', '7902309762'], 'payment_method_id': 'paypal_8516781'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='aarav_nguyen_7344',
        instruction='Your name is Aarav Nguyen and your email is aarav.nguyen1293@example.com and your zip code is 75268. You are independent, busy, outgoing, happy. Return #W7728728 via paypal_7859314: Wireless Earbuds;',
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W7728728', 'item_ids': ['8555936349'], 'payment_method_id': 'paypal_7859314'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='yusuf_garcia_1670',
        instruction="Your name is Yusuf Garcia and your email is yusuf.garcia2532@example.com and your zip code is 46202. You are messy, outgoing. For #W7639559, change address to {'order_id': '#W7639559', 'address1': '184 Elm Avenue', 'address2': 'Suite 770', 'city': 'Indianapolis', 'country': 'USA', 'state': 'IN', 'zip': '46202'}. For #W3691773, modify Water Bottle {'capacity': '500ml', 'color': 'green', 'material': 'stainless steel'} to {'capacity': '500ml', 'color': 'black', 'material': 'plastic'}; via gift_card_4303603.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W7639559', 'address1': '184 Elm Avenue', 'address2': 'Suite 770', 'city': 'Indianapolis', 'state': 'IN', 'country': 'USA', 'zip': '46202'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W3691773', 'item_ids': ['7533802601'], 'new_item_ids': ['3229676465'], 'payment_method_id': 'gift_card_4303603'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='olivia_ito_3591',
        instruction="Your name is Olivia Ito and your email is olivia.ito5204@example.com and your zip code is 80218. You are happy, pessimistic, relaxing, independent. For #W3657213, change payment to credit_card_9753331. For #W3657213, modify Digital Camera {'resolution': '24MP', 'storage': 'SD card', 'zoom': '3x'} to {'resolution': '30MP', 'storage': 'CF card', 'zoom': '5x'}; via paypal_8049766. Cancel order #W7941031 because no longer needed. For #W5442520, change payment to gift_card_7794233.",
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W3657213', 'payment_method_id': 'credit_card_9753331'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W3657213', 'item_ids': ['5996159312'], 'new_item_ids': ['6384525445'], 'payment_method_id': 'paypal_8049766'},
            ),
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W7941031', 'reason': 'no longer needed'},
            ),
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W5442520', 'payment_method_id': 'gift_card_7794233'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='yara_silva_7567',
        instruction="Your name is Yara Silva and your email is yara.silva2443@example.com and your zip code is 77159. You are optimistic, direct. For #W9034102, modify Water Bottle {'capacity': '500ml', 'color': 'black', 'material': 'stainless steel'} to {'capacity': '500ml', 'color': 'black', 'material': 'glass'}; via gift_card_7252880.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W9034102', 'item_ids': ['3453331371'], 'new_item_ids': ['8538875209'], 'payment_method_id': 'gift_card_7252880'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ivan_hernandez_6923',
        instruction='Your name is Ivan Hernandez and your email is ivan.hernandez1120@example.com and your zip code is 92133. You are confident, pessimistic. Return #W5838674 via gift_card_9368765: Laptop;',
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W5838674', 'item_ids': ['3478699712'], 'payment_method_id': 'gift_card_9368765'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='lei_li_6575',
        instruction='Your name is Lei Li and your email is lei.li8350@example.com and your zip code is 85033. You are polite, optimistic. Cancel order #W3414433 because no longer needed.',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W3414433', 'reason': 'no longer needed'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='daiki_muller_8062',
        instruction="Your name is Daiki Muller and your email is daiki.muller6278@example.com and your zip code is 94157. You are confident, direct. For #W7822344, modify Electric Kettle {'capacity': '1L', 'color': 'silver', 'material': 'stainless steel'} to {'capacity': '1.5L', 'color': 'black', 'material': 'plastic'}; via gift_card_8385925. Return #W5961635 via gift_card_8385925: Hiking Boots; Espresso Machine;",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W7822344', 'item_ids': ['8142779083'], 'new_item_ids': ['5428723833'], 'payment_method_id': 'gift_card_8385925'},
            ),
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W5961635', 'item_ids': ['6546364613', '4875647558'], 'payment_method_id': 'gift_card_8385925'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ava_lopez_2676',
        instruction='Your name is Ava Lopez and your email is ava.lopez3569@example.com and your zip code is 92168. You are logical, outgoing. Return #W2941275 via credit_card_7772870: Digital Camera; Water Bottle;',
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W2941275', 'item_ids': ['1804581713', '7843064651'], 'payment_method_id': 'credit_card_7772870'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ava_lopez_2676',
        instruction="Your name is Ava Lopez and your email is ava.lopez3569@example.com and your zip code is 92168. You are organized, curious. Return #W2941275 via credit_card_7772870: Digital Camera; Water Bottle; For #W5911003, change address to {'order_id': '#W5911003', 'address1': '325 Oak Street', 'address2': 'Suite 655', 'city': 'San Diego', 'country': 'USA', 'state': 'CA', 'zip': '92168'}.",
        actions=[
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W2941275', 'item_ids': ['1804581713', '7843064651'], 'payment_method_id': 'credit_card_7772870'},
            ),
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W5911003', 'address1': '325 Oak Street', 'address2': 'Suite 655', 'city': 'San Diego', 'state': 'CA', 'country': 'USA', 'zip': '92168'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='emma_santos_9753',
        instruction="Your name is Emma Santos and your email is emma.santos7683@example.com and your zip code is 78228. You are polite, busy, shy. For #W9903153, modify Water Bottle {'capacity': '750ml', 'color': 'red', 'material': 'stainless steel'} to {'capacity': '500ml', 'color': 'black', 'material': 'glass'}; via credit_card_5869505. For #W9655299, modify Sunglasses {'frame color': 'brown', 'frame material': 'plastic', 'lens color': 'brown', 'lens type': 'polarized'} to {'frame color': 'silver', 'frame material': 'metal', 'lens color': 'black', 'lens type': 'polarized'}; via gift_card_6023546.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W9903153', 'item_ids': ['6777246137'], 'new_item_ids': ['8538875209'], 'payment_method_id': 'credit_card_5869505'},
            ),
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W9655299', 'item_ids': ['9672174103'], 'new_item_ids': ['2198125883'], 'payment_method_id': 'gift_card_6023546'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='aarav_ito_1827',
        instruction="Your name is Aarav Ito and your email is aarav.ito1554@example.com and your zip code is 90131. You are sad, curious, logical, pessimistic. For #W2239230, modify Headphones {'color': 'red', 'connectivity': 'wireless', 'type': 'on-ear'} to {'color': 'white', 'connectivity': 'wireless', 'type': 'on-ear'}; via gift_card_1468632.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W2239230', 'item_ids': ['3104857380'], 'new_item_ids': ['9805150490'], 'payment_method_id': 'gift_card_1468632'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='lei_li_6575',
        instruction='Your name is Lei Li and your email is lei.li8350@example.com and your zip code is 85033. You are curious, independent, organized. Cancel order #W3414433 because no longer needed. Return #W6289770 via credit_card_4466831: Sunglasses;',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W3414433', 'reason': 'no longer needed'},
            ),
            Action(
                name='return_delivered_order_items',
                kwargs={'order_id': '#W6289770', 'item_ids': ['4548300368'], 'payment_method_id': 'credit_card_4466831'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='lei_li_6575',
        instruction="Your name is Lei Li and your email is lei.li8350@example.com and your zip code is 85033. You are relaxing, independent. For #W3189752, modify Electric Kettle {'capacity': '1L', 'color': 'white', 'material': 'glass'} to {'capacity': '1L', 'color': 'black', 'material': 'glass'}; via paypal_5914760.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W3189752', 'item_ids': ['5268233322'], 'new_item_ids': ['2323972008'], 'payment_method_id': 'paypal_5914760'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='yara_silva_7567',
        instruction='Your name is Yara Silva and your email is yara.silva2443@example.com and your zip code is 77159. You are happy, curious, direct. Cancel order #W9810810 because no longer needed.',
        actions=[
            Action(
                name='cancel_pending_order',
                kwargs={'order_id': '#W9810810', 'reason': 'no longer needed'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='noah_martin_5764',
        instruction="Your name is Noah Martin and your email is noah.martin8712@example.com and your zip code is 43090. You are happy, cautious. For #W1971958, exchange Mechanical Keyboard {'backlight': 'white', 'size': 'full size', 'switch type': 'clicky'} to {'backlight': 'none', 'size': '80%', 'switch type': 'linear'}; via paypal_7383471.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W1971958', 'item_ids': ['6342039236'], 'new_item_ids': ['1421289881'], 'payment_method_id': 'paypal_7383471'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='evelyn_patel_8882',
        instruction="Your name is Evelyn Patel and your email is evelyn.patel2010@example.com and your zip code is 28262. You are logical, happy. For #W3561024, change address to {'order_id': '#W3561024', 'address1': '749 Elm Avenue', 'address2': 'Suite 798', 'city': 'Los Angeles', 'country': 'USA', 'state': 'CA', 'zip': '90358'}.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W3561024', 'address1': '749 Elm Avenue', 'address2': 'Suite 798', 'city': 'Los Angeles', 'state': 'CA', 'country': 'USA', 'zip': '90358'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='anya_patel_3710',
        instruction='Your name is Anya Patel and your email is anya.patel9309@example.com and your zip code is 77256. You are polite, curious, sad. For #W4604258, change payment to credit_card_4142574.',
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W4604258', 'payment_method_id': 'credit_card_4142574'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='olivia_khan_9030',
        instruction='Your name is Olivia Khan and your email is olivia.khan2360@example.com and your zip code is 92110. You are busy, patient, happy, confident. For #W3840181, change payment to credit_card_7376788.',
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W3840181', 'payment_method_id': 'credit_card_7376788'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='lei_li_6575',
        instruction="Your name is Lei Li and your email is lei.li8350@example.com and your zip code is 85033. You are polite, creative. For #W6289770, exchange Luggage Set {'color': 'red', 'material': 'hardshell', 'piece count': '2-piece'} to {'color': 'blue', 'material': 'softshell', 'piece count': '3-piece'}; via credit_card_4466831.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W6289770', 'item_ids': ['8964750292'], 'new_item_ids': ['6301799585'], 'payment_method_id': 'credit_card_4466831'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='sophia_patel_6833',
        instruction="Your name is Sophia Patel and your email is sophia.patel9841@example.com and your zip code is 76169. You are cautious, relaxing. For #W7905419, modify Perfume {'gender': 'men', 'scent family': 'oriental', 'size': '100ml'} to {'gender': 'men', 'scent family': 'oriental', 'size': '30ml'}; via credit_card_6017489. For #W2923184, exchange Laptop {'color': 'black', 'processor': 'i7', 'ram': '32GB', 'screen size': '17-inch', 'storage': '1TB SSD'} to {'color': 'space grey', 'processor': 'i7', 'ram': '32GB', 'screen size': '15-inch', 'storage': '1TB SSD'}; via credit_card_6419343.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W7905419', 'item_ids': ['5421902839'], 'new_item_ids': ['1325156478'], 'payment_method_id': 'credit_card_6017489'},
            ),
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W2923184', 'item_ids': ['1684786391'], 'new_item_ids': ['6017636844'], 'payment_method_id': 'credit_card_6419343'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ivan_khan_7475',
        instruction='Your name is Ivan Khan and your email is ivan.khan6479@example.com and your zip code is 28243. You are confident, shy. For #W5782623, change payment to paypal_7729105.',
        actions=[
            Action(
                name='modify_pending_order_payment',
                kwargs={'order_id': '#W5782623', 'payment_method_id': 'paypal_7729105'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='raj_santos_9079',
        instruction="Your name is Raj Santos and your email is raj.santos4322@example.com and your zip code is 98157. You are organized, shy. For #W4680753, exchange Mechanical Keyboard {'backlight': 'RGB', 'size': '60%', 'switch type': 'clicky'} to {'backlight': 'RGB', 'size': '80%', 'switch type': 'linear'}; via paypal_2417743.",
        actions=[
            Action(
                name='exchange_delivered_order_items',
                kwargs={'order_id': '#W4680753', 'item_ids': ['9690244451'], 'new_item_ids': ['8484921793'], 'payment_method_id': 'paypal_2417743'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='james_johnson_9321',
        instruction="Your name is James Johnson and your email is james.johnson7869@example.com and your zip code is 60625. You are sad, busy, direct. For #W1006327, modify Action Camera {'color': 'black', 'resolution': '1080p', 'waterproof': 'yes'} to {'color': 'black', 'resolution': '4K', 'waterproof': 'yes'}; via credit_card_4998749.",
        actions=[
            Action(
                name='modify_pending_order_items',
                kwargs={'order_id': '#W1006327', 'item_ids': ['5925362855'], 'new_item_ids': ['6700049080'], 'payment_method_id': 'credit_card_4998749'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='ava_nguyen_6646',
        instruction="Your name is Ava Nguyen and your email is ava.nguyen2868@example.com and your zip code is 94128. You are cautious, logical, direct, busy. For #W9892465, change address to {'order_id': '#W9892465', 'address1': '814 Maple Drive', 'address2': 'Suite 313', 'city': 'San Francisco', 'country': 'USA', 'state': 'CA', 'zip': '94128'}. For #W8367380, change address to {'order_id': '#W8367380', 'address1': '373 Cedar Street', 'address2': 'Suite 830', 'city': 'Los Angeles', 'country': 'USA', 'state': 'CA', 'zip': '90450'}.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W9892465', 'address1': '814 Maple Drive', 'address2': 'Suite 313', 'city': 'San Francisco', 'state': 'CA', 'country': 'USA', 'zip': '94128'},
            ),
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W8367380', 'address1': '373 Cedar Street', 'address2': 'Suite 830', 'city': 'Los Angeles', 'state': 'CA', 'country': 'USA', 'zip': '90450'},
            ),
        ],
        outputs=[],
    ),
    Task(
        annotator="synthetic",
        user_id='yusuf_garcia_1670',
        instruction="Your name is Yusuf Garcia and your email is yusuf.garcia2532@example.com and your zip code is 46202. You are patient, flexible. For #W7639559, change address to {'order_id': '#W7639559', 'address1': '184 Elm Avenue', 'address2': 'Suite 770', 'city': 'Indianapolis', 'country': 'USA', 'state': 'IN', 'zip': '46202'}.",
        actions=[
            Action(
                name='modify_pending_order_address',
                kwargs={'order_id': '#W7639559', 'address1': '184 Elm Avenue', 'address2': 'Suite 770', 'city': 'Indianapolis', 'state': 'IN', 'country': 'USA', 'zip': '46202'},
            ),
        ],
        outputs=[],
    ),
]
