tools:
  - class_name: "verl.tools.tau_retail.find_user_id_by_email.FindUserIdByEmail"
    config: 
      type: native
    tool_schema:
      type: "function"
      function:
        name: "find_user_id_by_email"
        description: "Find user id by email. If the user is not found, the function will return an error message."
        parameters:
          type: "object"
          properties:
            email:
              type: "string"
              description: "The email of the user, such as 'something@example.com'."
          required: ["email"]
  - class_name: "verl.tools.tau_retail.find_user_id_by_name_zip.FindUserIdByNameZip"
    # Retrieve a user's ID using first/last name and zip code
    config:
      type: native
    tool_schema:
      type: "function"
      function:
        name: "find_user_id_by_name_zip"
        description: "Find user id by first name, last name, and zip code. If the user is not found, the function will return an error message. By default, find user id by email, and only call this function if the user is not found by email or cannot remember email."
        parameters:
          type: "object"
          properties:
            first_name:
              type: "string"
              description: "The first name of the customer, such as 'John'."
            last_name:
              type: "string"
              description: "The last name of the customer, such as 'Doe'."
            zip:
              type: "string"
              description: "The zip code of the customer, such as '12345'."
          required: ["first_name", "last_name", "zip"]
  - class_name: "verl.tools.tau_retail.get_order_details.GetOrderDetails"
    config: 
      type: native
    tool_schema:
      type: "function"
      function:
        name: "get_order_details"
        description: "Get the status and details of an order."
        parameters:
          type: "object"
          properties:
            order_id:
              type: "string"
              description: "The order id, such as '#W0000000'. Be careful there is a '#' symbol at the beginning of the order id."
          required: ["order_id"]
  - class_name: "verl.tools.tau_retail.get_user_details.GetUserDetails"
    config: 
      type: native
    tool_schema:
      type: "function"
      function:
        name: "get_user_details"
        description: "Get the details of a user, including their orders."
        parameters:
          type: "object"
          properties:
            user_id:
              type: "string"
              description: "The user id, such as 'sara_doe_496'."
          required: ["user_id"]
  - class_name: "verl.tools.tau_retail.get_product_details.GetProductDetails"
    config: 
      type: native
    tool_schema:
      type: "function"
      function:
        name: "get_product_details"
        description: "Get the inventory details of a product."
        parameters:
          type: "object"
          properties:
            product_id:
              type: "string"
              description: "The product id, such as '6086499569'. Be careful the product id is different from the item id."
          required: ["product_id"]
  - class_name: "verl.tools.tau_retail.exchange_delivered_order_items.ExchangeDeliveredOrderItems"
    config: 
      type: native
    tool_schema:
      type: "function"
      function:
        name: "exchange_delivered_order_items"
        description: "Exchange items in a delivered order."
        parameters:
          type: "object"
          properties:
            order_id:
              type: "string"
              description: "The order id, such as '#W0000000'. Be careful there is a '#' symbol at the beginning of the order id."
            item_ids:
              type: "array"
              description: "The item ids to be exchanged, such as ['6086499569', '6086499570']. Be careful the item id is different from the product id."
            new_item_ids:
              type: "array"
              description: "The new item ids to be exchanged for, such as ['6086499569', '6086499570']. Be careful the item id is different from the product id."
          required: ["order_id", "item_ids", "new_item_ids"]
  - class_name: "verl.tools.tau_retail.cancel_pending_order.CancelPendingOrder"
    config: 
      type: native
    tool_schema:
      type: "function"
      function:
        name: "cancel_pending_order"
        description: "Cancel a pending order."
        parameters:
          type: "object"
          properties:
            order_id:
              type: "string"
              description: "The order id, such as '#W0000000'. Be careful there is a '#' symbol at the beginning of the order id."
            reason:
              type: "string"
              description: "The reason for cancelling the order, such as 'no longer needed' or 'ordered by mistake'."
          required: ["order_id", "reason"]
